### ISSUE TITLE
Issues with local testing

### ISSUE THREAD

**Issue by lijianw2** [uts-cic/acawriter#87] opened 2022-04-29 21:09 UTC
![image](https://user-images.githubusercontent.com/32266814/166069048-95c556d7-5bce-4737-85a4-02f6d3d461be.png)

**Comment by genieza** [comment] 2022-08-29 16:01
I have the same issue, please let me know what to do

**Comment by andreyinkin** [comment] 2022-09-16 05:53
Looks like this issue was caused by mounted volumes for development purpose - fixed in the latest commit.

**Closed by andreyinkin** 2022-09-16 05:53 UTC
